apiVersion: kustomize.config.k8s.io/v1beta1
bases:
- components/java-quarkus-10/base
- components/java-quarkus-3/base
- components/java-quarkus-4/base
- components/java-quarkus-5/base
- components/java-quarkus-6/base
- components/java-quarkus-7/base
- components/java-quarkus-9/base
- components/java-quarkus/base
- components/nodejs/base
kind: Kustomization
