apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-quarkus-2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-quarkus-2
    app.kubernetes.io/part-of: my-application
  name: java-quarkus-2
  namespace: karthik-jk
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: java-quarkus-2
status:
  loadBalancer: {}
